### ISSUE TITLE
Slight scoring inconsistency between metrics

### ISSUE THREAD

**Issue by hunterhector** [conll/reference-coreference-scorers#2]
During a recent preparation of a shared task, I found that the metrics have slightly different behavior against no coreference case. MUC will report 0% F1 for coreference, while the rest (blanc, ceaf, bcub) reports 100%

A very small test case can be the following, we can check the behavior by running the scorer use this file against itself.
# begin document (0001); part 000

0001    0       A       (0)
0001    1       B       (1)
# end document

The inconsistency may hurt when one want to compute a document level average, the 0% score produced by MUC can make the result change dramatically. In addition, I think it is reasonable to score it as 100% when both the key and response are identical.

**Comment by sameer-pradhan** [comment]
hmm, this is a MUC edge case, where there are no links and both are singleton mentions. traditionally MUC score for this configuration is considered to be zero. i do understand your quandry while computing a document-level macro average for documents with all singletons. it does not seem correct to assign a MUC score of 1 for this case either. maybe one can have a special case during macro averaging and not consider the MUC score in that situation. assuming that you are averaging it with BCUBED and CEAF. if the latter two are 0.5, then the average should be (0.5 + 0.5)/2 = 0.5, instead of (1 + 0.5 + 0.5)/3 = 0.66.

**Comment by hunterhector** [comment]
If this is a MUC design decision, then I could simply add a special case where both side are all singletons. Thanks for the suggestion.

**Comment by sameer-pradhan** [comment]
i believe that would be the best way to proceed.
let me know in case you run into any such unforeseen circumstances.
